name: Sample Four
on: 
  workflow_dispatch:
jobs:
  code-block:
    env:
      DETAILS: 'true'  # Set to 'false' to disable details tag
    name: Code Block Sample
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        id: setup
        run: |
          # Create a path to save the summary.
          echo "summary=${{ runner.temp }}/summary.md" >> $GITHUB_OUTPUT

      - name: Output to step summary [title]
        run: |
          echo "# Build Summary" > ${{ steps.setup.outputs.summary }}

      - name: Output to step summary [details start tag]
        if: ${{ env.DETAILS == 'true' }}
        run: |
          echo "<details>" >> ${{ steps.setup.outputs.summary }}
          echo "<summary>To manually download artifact from the command-line, please run the following command</summary>" >> ${{ steps.setup.outputs.summary }}
          echo "" >> ${{ steps.setup.outputs.summary }}

      - name: Output to step summary [body]
        run: |
          echo "" >> ${{ steps.setup.outputs.summary }}  # Blank line for spacing
          echo 'foo' >> ${{ steps.setup.outputs.summary }}
          echo '```json' >> ${{ steps.setup.outputs.summary }}
          echo '{ "test": "bar" }' >> ${{ steps.setup.outputs.summary }}
          echo '```' >> ${{ steps.setup.outputs.summary }}

      - name: Output to step summary [details end tag]
        if: ${{ env.DETAILS == 'true' }}
        run: |
          echo "" >> ${{ steps.setup.outputs.summary }}
          echo "</details>" >> ${{ steps.setup.outputs.summary }}

      - name: Output to step summary
        shell: bash
        run: |
          cat ${{ steps.setup.outputs.summary }}
          cat ${{ steps.setup.outputs.summary }} >> $GITHUB_STEP_SUMMARY
